version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "javascript"
    directory: "/"
    schedule:
      interval: "weekly"
